on: [push]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run linter
      shell: 'script -q -e -c "bash {0}"'
      run: make lint

    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: make test
