---
name: ci
permissions:
  pull-requests: read

on:
  push:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run linter
      shell: 'script -q -e -c "bash {0}"'
      run: make lint

    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: make test
